
// Warning! This file is autogenerated.
#include <boost/text/collation_tailoring.hpp>
#include <boost/text/collate.hpp>
#include <boost/text/data/all.hpp>

#include <gtest/gtest.h>

using namespace boost::text;

auto const error = [](string const & s) { std::cout << s; };
auto const warning = [](string const & s) {};

tailored_collation_element_table const & table()
{
    static tailored_collation_element_table retval =
        make_tailored_collation_element_table(
            data::se::standard_collation_tailoring(),
            "se::standard_collation_tailoring()", error, warning);
    return retval;
}
TEST(tailoring, se_standard_000_001)
{
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e1),
        std::vector<uint32_t>(1, 0x00c1),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e1),
        std::vector<uint32_t>(1, 0x00c1),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0062),
        std::vector<uint32_t>(1, 0x00c1),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x010d),
        std::vector<uint32_t>(1, 0x010c),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x010d),
        std::vector<uint32_t>(1, 0x010c),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0064),
        std::vector<uint32_t>(1, 0x010c),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x010c),
        std::vector<uint32_t>(1, 0x0292),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0064),
        std::vector<uint32_t>(1, 0x0292),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0292),
        std::vector<uint32_t>(1, 0x01b7),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0292),
        std::vector<uint32_t>(1, 0x01b7),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0064),
        std::vector<uint32_t>(1, 0x01b7),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01b7),
        std::vector<uint32_t>(1, 0x01ef),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0064),
        std::vector<uint32_t>(1, 0x01ef),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01ef),
        std::vector<uint32_t>(1, 0x01ee),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01ef),
        std::vector<uint32_t>(1, 0x01ee),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0064),
        std::vector<uint32_t>(1, 0x01ee),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0111),
        std::vector<uint32_t>(1, 0x0110),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0111),
        std::vector<uint32_t>(1, 0x0110),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0065),
        std::vector<uint32_t>(1, 0x0110),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0110),
        std::vector<uint32_t>(1, 0x00f0),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0110),
        std::vector<uint32_t>(1, 0x00f0),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0065),
        std::vector<uint32_t>(1, 0x00f0),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f0),
        std::vector<uint32_t>(1, 0x00d0),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f0),
        std::vector<uint32_t>(1, 0x00d0),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0065),
        std::vector<uint32_t>(1, 0x00d0),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e7),
        std::vector<uint32_t>(1, 0x01e6),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e7),
        std::vector<uint32_t>(1, 0x01e6),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0068),
        std::vector<uint32_t>(1, 0x01e6),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e6),
        std::vector<uint32_t>(1, 0x01e5),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0068),
        std::vector<uint32_t>(1, 0x01e5),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e5),
        std::vector<uint32_t>(1, 0x01e4),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e5),
        std::vector<uint32_t>(1, 0x01e4),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0068),
        std::vector<uint32_t>(1, 0x01e4),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e9),
        std::vector<uint32_t>(1, 0x01e8),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01e9),
        std::vector<uint32_t>(1, 0x01e8),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006c),
        std::vector<uint32_t>(1, 0x01e8),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x014b),
        std::vector<uint32_t>(1, 0x014a),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x014b),
        std::vector<uint32_t>(1, 0x014a),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006f),
        std::vector<uint32_t>(1, 0x014a),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x014a),
        std::vector<uint32_t>(1, 0x0144),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x014a),
        std::vector<uint32_t>(1, 0x0144),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006f),
        std::vector<uint32_t>(1, 0x0144),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0144),
        std::vector<uint32_t>(1, 0x0143),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0144),
        std::vector<uint32_t>(1, 0x0143),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006f),
        std::vector<uint32_t>(1, 0x0143),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0143),
        std::vector<uint32_t>(1, 0x00f1),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0143),
        std::vector<uint32_t>(1, 0x00f1),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006f),
        std::vector<uint32_t>(1, 0x00f1),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f1),
        std::vector<uint32_t>(1, 0x00d1),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f1),
        std::vector<uint32_t>(1, 0x00d1),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x006f),
        std::vector<uint32_t>(1, 0x00d1),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0161),
        std::vector<uint32_t>(1, 0x0160),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0161),
        std::vector<uint32_t>(1, 0x0160),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0074),
        std::vector<uint32_t>(1, 0x0160),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0167),
        std::vector<uint32_t>(1, 0x0166),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0167),
        std::vector<uint32_t>(1, 0x0166),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0075),
        std::vector<uint32_t>(1, 0x0166),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0166),
        std::vector<uint32_t>(1, 0x00fe),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0166),
        std::vector<uint32_t>(1, 0x00fe),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0075),
        std::vector<uint32_t>(1, 0x00fe),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00fe),
        std::vector<uint32_t>(1, 0x00de),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00fe),
        std::vector<uint32_t>(1, 0x00de),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0075),
        std::vector<uint32_t>(1, 0x00de),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0079),
        std::vector<uint32_t>(1, 0x00fc),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0079),
        std::vector<uint32_t>(1, 0x00fc),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00fc),
        std::vector<uint32_t>(1, 0x00dc),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00fc),
        std::vector<uint32_t>(1, 0x00dc),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00dc),
        std::vector<uint32_t>(1, 0x0171),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00dc),
        std::vector<uint32_t>(1, 0x0171),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0171),
        std::vector<uint32_t>(1, 0x0170),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0171),
        std::vector<uint32_t>(1, 0x0170),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x017e),
        std::vector<uint32_t>(1, 0x017d),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x017e),
        std::vector<uint32_t>(1, 0x017d),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x017d),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x017d),
        std::vector<uint32_t>(1, 0x00f8),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00f8),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f8),
        std::vector<uint32_t>(1, 0x00d8),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f8),
        std::vector<uint32_t>(1, 0x00d8),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00d8),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d8),
        std::vector<uint32_t>(1, 0x0153),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d8),
        std::vector<uint32_t>(1, 0x0153),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0153),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0153),
        std::vector<uint32_t>(1, 0x0152),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0153),
        std::vector<uint32_t>(1, 0x0152),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0152),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0152),
        std::vector<uint32_t>(1, 0x00e6),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00e6),
        table(), collation_strength::quaternary),
        1);
}

TEST(tailoring, se_standard_000_002)
{
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e6),
        std::vector<uint32_t>(1, 0x00c6),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e6),
        std::vector<uint32_t>(1, 0x00c6),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00c6),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c6),
        std::vector<uint32_t>(1, 0x00e5),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00e5),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e5),
        std::vector<uint32_t>(1, 0x00c5),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e5),
        std::vector<uint32_t>(1, 0x00c5),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00c5),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c5),
        std::vector<uint32_t>(1, 0x0227),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c5),
        std::vector<uint32_t>(1, 0x0227),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0227),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0227),
        std::vector<uint32_t>(1, 0x0226),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0227),
        std::vector<uint32_t>(1, 0x0226),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0226),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0226),
        std::vector<uint32_t>(1, 0x00e4),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00e4),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e4),
        std::vector<uint32_t>(1, 0x00c4),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e4),
        std::vector<uint32_t>(1, 0x00c4),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00c4),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c4),
        std::vector<uint32_t>(1, 0x00e3),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c4),
        std::vector<uint32_t>(1, 0x00e3),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00e3),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e3),
        std::vector<uint32_t>(1, 0x00c3),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00e3),
        std::vector<uint32_t>(1, 0x00c3),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00c3),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00c3),
        std::vector<uint32_t>(1, 0x00f6),
        table(), collation_strength::primary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00f6),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f6),
        std::vector<uint32_t>(1, 0x00d6),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f6),
        std::vector<uint32_t>(1, 0x00d6),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00d6),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d6),
        std::vector<uint32_t>(1, 0x0151),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d6),
        std::vector<uint32_t>(1, 0x0151),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0151),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0151),
        std::vector<uint32_t>(1, 0x0150),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0151),
        std::vector<uint32_t>(1, 0x0150),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x0150),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0150),
        std::vector<uint32_t>(1, 0x00f5),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x0150),
        std::vector<uint32_t>(1, 0x00f5),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00f5),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f5),
        std::vector<uint32_t>(1, 0x00d5),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f5),
        std::vector<uint32_t>(1, 0x00d5),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00d5),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d5),
        std::vector<uint32_t>(1, 0x00f4),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d5),
        std::vector<uint32_t>(1, 0x00f4),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00f4),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f4),
        std::vector<uint32_t>(1, 0x00d4),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00f4),
        std::vector<uint32_t>(1, 0x00d4),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x00d4),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d4),
        std::vector<uint32_t>(1, 0x01eb),
        table(), collation_strength::secondary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x00d4),
        std::vector<uint32_t>(1, 0x01eb),
        table(), collation_strength::primary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x01eb),
        table(), collation_strength::quaternary),
        1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01eb),
        std::vector<uint32_t>(1, 0x01ea),
        table(), collation_strength::tertiary),
        -1);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01eb),
        std::vector<uint32_t>(1, 0x01ea),
        table(), collation_strength::secondary),
        0);
    EXPECT_EQ(collate(
        std::vector<uint32_t>(1, 0x01c0),
        std::vector<uint32_t>(1, 0x01ea),
        table(), collation_strength::quaternary),
        1);
}
