// Warning! This file is autogenerated.
#ifndef BOOST_TEXT_DATA_BE_HPP
#define BOOST_TEXT_DATA_BE_HPP

#include <boost/text/string_view.hpp>


namespace boost { namespace text { namespace data { namespace be {

inline string_view standard_collation_tailoring()
{
    return string_view(
"  \n"
"[reorder Cyrl]\n"
"&\xd0\x95<\xd1\x91<<<\xd0\x81\n"
"&\xd1\x83<\xd1\x9e<<<\xd0\x8e\n"
"  \n");
}


}}}}

#endif
