// Warning! This file is autogenerated.
#ifndef BOOST_TEXT_DATA_BE_HPP
#define BOOST_TEXT_DATA_BE_HPP

#include <boost/text/string_view.hpp>


namespace boost { namespace text { namespace data { namespace be {

inline string_view standard_collation_tailoring()
{
    return string_view(
u8"  \n"
u8"[reorder Cyrl]\n"
u8"&Е<ё<<<Ё\n"
u8"&у<ў<<<Ў\n"
u8"  \n");
}


}}}}

#endif
