// Warning! This file is autogenerated.
#ifndef BOOST_TEXT_DATA_ET_HPP
#define BOOST_TEXT_DATA_ET_HPP


namespace boost { namespace text { namespace data { namespace et {

inline string_view standard_collation_tailoring()
{
    return string_view(
        R"(  
&[before 1]T<š<<<Š<z<<<Z<ž<<<Ž
&[before 1]X<õ<<<Õ<ä<<<Ä<ö<<<Ö<ü<<<Ü
  )"
    );
}


}}}}

#endif
