// Warning! This file is autogenerated.
#ifndef BOOST_TEXT_DATA_HSB_HPP
#define BOOST_TEXT_DATA_HSB_HPP

#include <boost/text/string_view.hpp>


namespace boost { namespace text { namespace data { namespace hsb {

inline string_view standard_collation_tailoring()
{
    return string_view(
u8"  \n"
u8"&C<č<<<Č<ć<<<Ć\n"
u8"&E<ě<<<Ě\n"
u8"&H<ch<<<cH<<<Ch<<<CH\n"
u8"&[before 1] L<ł<<<Ł\n"
u8"&R<ř<<<Ř\n"
u8"&S<š<<<Š\n"
u8"&Z<ž<<<Ž<ź<<<Ź\n"
u8"  \n");
}


}}}}

#endif
